Import grub2_2.02~beta3-3
Pristine import grub2_2.02~beta3-3.debian.tar.xz but remove all
patches, since we'll keep them on the main branch.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -10,17 +10,18 @@ DEB_HOST_ARCH ?= $(shell dpkg-architecture -qDEB_HOST_ARCH 2>/dev/null)
 DEB_HOST_ARCH_OS ?= $(shell dpkg-architecture -qDEB_HOST_ARCH_OS 2>/dev/null)
 DEB_HOST_ARCH_CPU ?= $(shell dpkg-architecture -qDEB_HOST_ARCH_CPU 2>/dev/null)
 
-HOST_CFLAGS := -g -Wall -Wno-error=unused-result
-
-ifneq (,$(findstring noopt,$(DEB_BUILD_OPTIONS)))
-	HOST_CFLAGS += -O0
-else
-	HOST_CFLAGS += -O2
-endif
+HOST_CPPFLAGS := $(shell dpkg-buildflags --get CPPFLAGS)
+# -O3 (default on Ubuntu ppc64el) introduces various -Werror failures, and
+# isn't worth it here.
+HOST_CFLAGS := -Wall -Wno-error=unused-result $(shell dpkg-buildflags --get CFLAGS | perl -pe 's/-O3\b/-O2/')
+HOST_LDFLAGS := $(shell dpkg-buildflags --get LDFLAGS)
 
 unexport CFLAGS
+export HOST_CPPFLAGS
 export HOST_CFLAGS
+export HOST_LDFLAGS
 export TARGET_CPPFLAGS := -Wno-unused-but-set-variable
+export TARGET_LDFLAGS := -no-pie
 
 ifeq (,$(shell which qemu-system-i386 2>/dev/null))
 with_check := no
@@ -28,9 +29,13 @@ else
 with_check := yes
 endif
 
-CC := gcc-4.9
+CC := gcc-6
 
-confflags = PACKAGE_VERSION="$(deb_version)" PACKAGE_STRING="GRUB $(deb_version)" CC=$(CC) TARGET_CC=$(CC) --enable-grub-mkfont
+confflags = \
+	PACKAGE_VERSION="$(deb_version)" PACKAGE_STRING="GRUB $(deb_version)" \
+	CC=$(CC) TARGET_CC=$(CC) \
+	--enable-grub-mkfont \
+	--disable-grub-emu-usb
 substvars =
 
 AUTOGEN_DEB_FILES = config templates preinst postinst postrm dirs install links maintscript
@@ -95,6 +100,18 @@ DEFAULT_HIDDEN_TIMEOUT_BOOL := false
 endif
 
 SB_PACKAGE :=
+ifeq (yes,$(shell dpkg-vendor --derives-from Ubuntu && echo yes))
+ifeq ($(DEB_HOST_ARCH),amd64)
+SB_PACKAGE := grub-efi-amd64
+SB_PLATFORM := x86_64-efi
+SB_EFI_NAME := x64
+endif
+ifeq ($(DEB_HOST_ARCH),arm64)
+SB_PACKAGE := grub-efi-arm64
+SB_PLATFORM := arm64-efi
+SB_EFI_NAME := aa64
+endif
+endif
 
 %:
 	dh $@ --parallel
@@ -128,7 +145,7 @@ debian/stamps/autogen: autogen.sh configure.ac Makefile.util.def grub-core/Makef
 	set -e; for extra in 915resolution ntldr-img; do \
 		cp -a debian/grub-extras/$$extra debian/grub-extras-enabled/; \
 	done
-	env -u DH_OPTIONS GRUB_CONTRIB=$(CURDIR)/debian/grub-extras-enabled NOCONFIGURE=1 \
+	env -u DH_OPTIONS GRUB_CONTRIB=$(CURDIR)/debian/grub-extras-enabled \
 		dh_autoreconf -- ./autogen.sh
 	touch $@
 
@@ -202,7 +219,7 @@ debian/stamps/build-grub-xen-host: debian/stamps/build-grub-xen-host-i386 debian
 debian/stamps/build-grub-pc: debian/stamps/configure-grub-pc
 	dh_auto_build
 ifeq ($(with_check), yes)
-	LC_CTYPE=C.UTF-8 PATH="$$PATH:/sbin:/usr/sbin" VERBOSE=1 dh_auto_test --max-parallel=1
+	LC_MESSAGES=C.UTF-8 LC_CTYPE=C.UTF-8 PATH="$$PATH:/sbin:/usr/sbin" VERBOSE=1 dh_auto_test --max-parallel=1
 endif
 	touch $@
 
@@ -252,7 +269,8 @@ debian/stamps/build-grub-rescue-pc: debian/stamps/build-grub-pc
 		--locale-directory=$(CURDIR)/obj/grub-rescue-pc/grub-core/po \
 		--output=$(CURDIR)/obj/grub-rescue-pc/grub-rescue-floppy.img \
 		--compress=xz \
-		-- -no-pad $(CURDIR)/obj/grub-rescue-pc/rescue-disk
+		-no-pad \
+		$(CURDIR)/obj/grub-rescue-pc/rescue-disk
 	touch $@
 
 platform_subst = \
@@ -393,27 +411,37 @@ ifeq (yes,$(shell dpkg-vendor --derives-from Ubuntu && echo yes))
 		$(CURDIR)/debian/$(package)/etc/pm/sleep.d/10_grub-common
 endif
 
+NON_PLATFORM_PACKAGES = $(filter grub2 grub-linuxbios grub-efi grub-rescue-pc grub-firmware-qemu grub-xen-host,$(BUILD_PACKAGES))
+COMMON_PLATFORM_PACKAGES = $(filter grub-common grub2-common grub-theme-starfield grub-mount-udeb,$(BUILD_PACKAGES))
+PLATFORM_PACKAGES = $(filter grub-pc grub-efi-ia32 grub-efi-amd64 grub-efi-ia64 grub-efi-arm grub-efi-arm64 grub-ieee1275 grub-coreboot grub-uboot grub-xen grub-yeeloong,$(BUILD_PACKAGES))
+
 override_dh_install:
-	dh_install -pgrub2 -pgrub-linuxbios -pgrub-efi -pgrub-rescue-pc -pgrub-firmware-qemu -pgrub-xen-host
-	dh_install -pgrub-common -pgrub2-common -pgrub-theme-starfield -pgrub-mount-udeb --sourcedir=debian/tmp-grub-$(COMMON_PLATFORM)
+ifneq (,$(NON_PLATFORM_PACKAGES))
+	dh_install $(patsubst %,-p%,$(NON_PLATFORM_PACKAGES))
+endif
+	dh_install $(patsubst %,-p%,$(COMMON_PLATFORM_PACKAGES)) --sourcedir=debian/tmp-grub-$(COMMON_PLATFORM)
 	rm -f debian/grub2-common/usr/share/info/dir*
 	rm -f debian/grub-theme-starfield/usr/share/grub/themes/starfield/COPYING.CC-BY-SA-3.0
-	set -e; for package in grub-pc grub-efi-ia32 grub-efi-amd64 grub-efi-ia64 grub-efi-arm grub-efi-arm64 grub-ieee1275 grub-coreboot grub-uboot grub-xen grub-yeeloong; do \
+ifneq (,$(PLATFORM_PACKAGES))
+	set -e; for package in $(PLATFORM_PACKAGES); do \
 		dh_install -p$$package --sourcedir=debian/tmp-$$package; \
 		dh_install -p$$package-bin --sourcedir=debian/tmp-$$package; \
 		dh_install -p$$package-dbg --sourcedir=debian/tmp-$$package; \
 	done
+endif
+ifneq (,$(filter grub-emu,$(BUILD_PACKAGES)))
 	dh_install -pgrub-emu --sourcedir=debian/tmp-grub-emu
 	dh_install -pgrub-emu-dbg --sourcedir=debian/tmp-grub-emu
+endif
 ifneq (,$(filter grub2-common,$(BUILD_PACKAGES)))
 	sed -i \
 		-e "s/@DEFAULT_CMDLINE@/$(DEFAULT_CMDLINE)/g" \
 		-e "s/@DEFAULT_TIMEOUT@/$(DEFAULT_TIMEOUT)/g" \
 		debian/grub2-common/usr/share/grub/default/grub
-endif
 ifneq (,$(DEFAULT_HIDDEN_TIMEOUT))
 	perl -pi -e 's/^GRUB_TIMEOUT=.*/GRUB_HIDDEN_TIMEOUT=0\nGRUB_HIDDEN_TIMEOUT_QUIET=true\n$$&/' \
 		debian/grub2-common/usr/share/grub/default/grub
+endif
 endif
 ifeq (yes,$(shell dpkg-vendor --derives-from Ubuntu && echo yes))
 ifneq (,$(filter grub-pc,$(BUILD_PACKAGES)))
@@ -423,8 +451,8 @@ endif
 endif
 
 override_dh_installdocs:
-	dh_installdocs -pgrub-common -pgrub-rescue-pc -pgrub-firmware-qemu -pgrub-xen-host -A AUTHORS NEWS README THANKS TODO
-	dh_installdocs -Ngrub-common -Ngrub-rescue-pc -Ngrub-firmware-qemu -Ngrub-xen-host --link-doc=grub-common
+	dh_installdocs $(patsubst %,-p%,$(filter grub-common grub-rescue-pc grub-firmware-qemu grub-xen-host,$(BUILD_PACKAGES))) -A AUTHORS NEWS README THANKS TODO
+	dh_installdocs --remaining-packages --link-doc=grub-common
 
 ifeq ($(FLICKER_FREE_BOOT),yes)
 override_dh_installinit:
@@ -444,24 +472,17 @@ override_dh_shlibdeps:
 	dh_shlibdeps -X.module
 
 ifeq (yes,$(shell dpkg-vendor --derives-from Ubuntu && echo yes))
-LEGACY_DOC_CONFLICTS := grub-doc (<< 0.97-29ubuntu60), grub-legacy-doc (<< 0.97-29ubuntu60)
+LEGACY_DOC_BR := grub-doc (<< 0.97-29ubuntu60), grub-legacy-doc (<< 0.97-29ubuntu60)
 else
-LEGACY_DOC_CONFLICTS := grub-doc (<< 0.97-32), grub-legacy-doc (<< 0.97-59)
+LEGACY_DOC_BR := grub-doc (<< 0.97-32), grub-legacy-doc (<< 0.97-59)
 endif
 
 override_dh_gencontrol:
-	dh_gencontrol -- \
-		-Vlegacy-doc-conflicts="$(LEGACY_DOC_CONFLICTS)" $(substvars)
+	dh_gencontrol -- -Vlegacy-doc-br="$(LEGACY_DOC_BR)" $(substvars)
 
 TARNAME := grub2_$(deb_version)_$(DEB_HOST_ARCH).tar.gz
 
 override_dh_builddeb:
-	mkdir -p debian/grub-efi-amd64-image/boot/efi/EFI/BOOT/
-	debian/build-sa-efi-images \
-		obj/grub-$(COMMON_PLATFORM)/grub-mkstandalone \
-		obj/grub-efi-amd64/grub-core \
-		debian/grub-efi-amd64-image/boot/efi/EFI/endless/ \
-		x86_64-efi x64 debian/endless-uefi-grub.cfg
 	dh_builddeb -- -Zxz
 ifneq (,$(SB_PACKAGE))
 	debian/build-efi-images \
